
-- 1. Tabla de Usuarios (Profesores)
CREATE TABLE users (
                       id_user INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(100) NOT NULL,
                       last_name VARCHAR(100) NOT NULL,
                       email VARCHAR(150) UNIQUE NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tabla de Estudiantes
CREATE TABLE students (
                          id_student INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          first_name VARCHAR(100) NOT NULL,
                          last_name VARCHAR(100) NOT NULL,
                          dni VARCHAR(20) UNIQUE NOT NULL,
                          birth_date DATE,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Tabla de Periodos (Ciclo Escolar)
CREATE TABLE periods (
                         id_period INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(50) NOT NULL,
                         start_date DATE NOT NULL,
                         end_date DATE NOT NULL,
                         is_closed BOOLEAN DEFAULT FALSE,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT check_dates CHECK (end_date > start_date)
);