-- 4. Tabla de Cursos (Materias)
CREATE TABLE courses (
                         id_course INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         id_teacher INT REFERENCES users(id_user) ON DELETE SET NULL, -- Clave foránea numérica
                         name VARCHAR(100) NOT NULL,
                         description TEXT,
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                         updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. Tabla Intermedia: Course Periods (Grados/Secciones por año)
CREATE TABLE course_periods (
                                id_course_period INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                id_course INT NOT NULL REFERENCES courses(id_course) ON DELETE CASCADE,
                                id_period INT NOT NULL REFERENCES periods(id_period) ON DELETE CASCADE,
                                section VARCHAR(10),
                                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);