-- 6. Tabla de Inscripciones (Relación Alumno - Grado)
CREATE TABLE enrollments (
                             id_enrollment INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             id_student INT NOT NULL REFERENCES students(id_student) ON DELETE CASCADE,
                             id_course_period INT NOT NULL REFERENCES course_periods(id_course_period) ON DELETE CASCADE,
                             status VARCHAR(20) DEFAULT 'active',
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             UNIQUE(id_student, id_course_period)
);

-- 7. Tabla de Asistencias (Con PK compuesta numérica)
CREATE TABLE attendances (
                             id_student INT NOT NULL REFERENCES students(id_student) ON DELETE CASCADE,
                             id_course_period INT NOT NULL REFERENCES course_periods(id_course_period) ON DELETE CASCADE,
                             id_teacher INT NOT NULL REFERENCES users(id_user),
                             date DATE NOT NULL,
                             did_attend BOOLEAN DEFAULT TRUE,
                             observation VARCHAR(255),
                             created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                             updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                             PRIMARY KEY (id_student, id_course_period, date)
);

-- 8. Tabla de Actividades (Tareas/Exámenes)
CREATE TABLE activities (
                            id_activity INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            id_course_period INT NOT NULL REFERENCES course_periods(id_course_period) ON DELETE CASCADE,
                            name VARCHAR(100) NOT NULL,
                            weight DECIMAL(5,2),
                            due_date DATE,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 9. Tabla de Calificaciones (Letras para Primaria)
CREATE TABLE grades (
                        id_activity INT NOT NULL REFERENCES activities(id_activity) ON DELETE CASCADE,
                        id_student INT NOT NULL REFERENCES students(id_student) ON DELETE CASCADE,
                        value VARCHAR(5) NOT NULL,
                        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                        PRIMARY KEY (id_activity, id_student)
);