name: learnix-application

services:
  mysql:
    image: mysql:8.0
    container_name: learnix-database
    environment:
      - MYSQL_USER=${MYSQL_USER:-learnix_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-learnix_password}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-learnix_database}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u ${MYSQL_USER:-learnix_user} --password=${MYSQL_PASSWORD:-learnix_password}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - learnix-network

  backend:
    build: web-app
    profiles:
      - dev
    image: learnix-backend
    container_name: learnix-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${DATABASE_URL:-jdbc:mysql://mysql:3306/learnix_database}
      - MYSQL_USER=${MYSQL_USER:-learnix_user}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-learnix_password}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - learnix-network

networks:
  learnix-network:
    driver: bridge