spring:
  application:
    name: LearnixWeb
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/learnix_database}
    username: ${POSTGRES_USER:learnix_user}
    password: ${POSTGRES_PASSWORD:learnix_password}
    hikari:
      connection-timeout: 5000
      initialization-fail-timeout: 5000
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true
server:
  port: 8083